#!/usr/bin/env node

// dependencies
var app = require('./app');
var debug = require('debug')('server');
var http = require('http');


var port = app.get('port') || 3000;
var bind = typeof port === 'string'? 'pipe ' + port : 'port ' + port;


// setup HTTP server
var server = http.createServer(app);
server.listen(port);
server.on('error', onError);
server.on('listening', onListening);


// event listeners
function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

function onListening() {
  debug('Listening on ' + bind);
}
